// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPrWxjTI6FPDrY4yVVG-nBxbU0b3uBbII',
    appId: '1:652835192195:web:81b15a70326639f2db0ab6',
    messagingSenderId: '652835192195',
    projectId: 'timetable-app-d0d44',
    authDomain: 'timetable-app-d0d44.firebaseapp.com',
    storageBucket: 'timetable-app-d0d44.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL8Yzij5PYvnVeGcxJrb2PGrcq9uqkoW4',
    appId: '1:652835192195:android:7f2dfd1bd33748d8db0ab6',
    messagingSenderId: '652835192195',
    projectId: 'timetable-app-d0d44',
    storageBucket: 'timetable-app-d0d44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHBU8a_9Cvgoxh8n8fwoGojmZt---SToM',
    appId: '1:652835192195:ios:00dbb1c9525babe4db0ab6',
    messagingSenderId: '652835192195',
    projectId: 'timetable-app-d0d44',
    storageBucket: 'timetable-app-d0d44.appspot.com',
    iosBundleId: 'com.example.timetableApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPrWxjTI6FPDrY4yVVG-nBxbU0b3uBbII',
    appId: '1:652835192195:web:d588a4c5b2dfd5bfdb0ab6',
    messagingSenderId: '652835192195',
    projectId: 'timetable-app-d0d44',
    authDomain: 'timetable-app-d0d44.firebaseapp.com',
    storageBucket: 'timetable-app-d0d44.appspot.com',
  );
}
